### ISSUE TITLE
[Integrate] As a user, I can log in with a single button

### ISSUE THREAD

**Issue by doannimble** [nimblehq/survey-api-sdk-android#6]
## Why
On the `sample-app`, the user will be able to log in with just 1 click for the demo purpose.

## Acceptance Criteria
- When the user clicks on the `Login` button, invoke an API call to obtain the access token using the credential we stored from the BuildConfig.
- Once logged in successfully, display a simple Toast message to inform the user; the same when login unsuccessfully.

**Comment by sleepylee** [comment]
I propose to change the ticket name here as well, you can read more from the Product document we provided, similar from the Story issue template.
The story should tell at the product level, instead of the developer level. As you can see, I don't mention `ViewModel` or how you plan to connect the Backend with the UI, it is the developer's choice of implementation, and when writing Backlog ticket, we should keep it at the Product point of view 😇 
```
[Integrate] As a user, I can log in with a single button

## Why
On the `sample-app`, the user will be able to log in with just 1 click for the demo purpose.

## Acceptance Criteria
- When the user clicks on the `Login` button, invoke an API call to obtain the access token using the credential we stored from the BuildConfig.
- Once logged in successfully, display a simple Toast message to inform the user; the same when login unsuccessfully.
```
